
print("      _     ")
print("     / \    ")
print("    / _ \   ")
print("   / ___ \  ")
print("  /_/___\_\ ")

print("   ____     ")
print("  | __ )    ")
print("  |  _ \    ")
print("  | |_) |   ")
print("  |____/    ")

print("    ____    ")
print("   / ___|   ")
print("   | |      ")
print("   | |__    ")
print("   \____|   ")
  
print("   ____     ")
print("  |  _ \    ")
print("  | | | |   ")
print("  | |_| |   ")
print("  |____/    ")

print("   _____    ")
print("  | ____|   ") 
print("  |  _|     ")
print("  | |___    ")
print("  |_____|   ")

print("   _____    ")
print("  |  ___|   ")
print("  | |_      ")
print("  |  _|     ")
print("  |_|       ")

print("    ____    ")
print("   / ___|   ")
print("  | |  _    ")
print("  | |_| |   ")
print("   \____|   ")

print("   _   _    ")
print("  | | | |   ")
print("  | |_| |   ")
print("  |  _  |   ")
print("  |_|_|_|   ")

print("   ___      ")
print("  |_ _|     ")
print("   | |      ")
print("   | |      ")
print("  |___|     ")

print("       _    ")
print("      | |   ")
print("   _  | |   ")
print("  | |_| |   ")
print("   \___/    ")

print("   _  _     ")
print("  | |/ /    ")
print("  | ' /     ")
print("  | . \     ")
print("  |_|\_\    ")

print("   _        ")
print("  | |       ")
print("  | |       ")
print("  | |___    ")
print("  |_____|   ")

print("   __  __   ")
print("  |  \/  |  ")
print("  | |\/| |  ")
print("  | |  | |  ")
print("  |_|__|_|  ")
  

print("   _   _    ")
print("  | \ | |   ")
print("  |  \| |   ")
print("  | |\  |   ")
print("  |_|_\_|   ")

print("    ___    ")
print("   / _ \   ")
print("  | | | |  ")
print("  | |_| |  ")
print("   \___/   ")

print("   ____    ")
print("  |  _ \   ")
print("  | |_) |  ")
print("  |  __/   ")
print("  |_|      ")

print("    ___    ")
print("   / _ \   ")
print("  | | | |  ")
print("  | |_| |  ")
print("   \__\_\  ")

print("   ____    ")
print("  |  _ \   ")
print("  | |_) |  ")
print("  |  _ <   ")
print("  |_|_\_\  ")

print("   ____    ")
print("  / ___|   ")
print("  \___ \   ")
print("   ___) |  ")
print("  |____/   ")

print("   _____   ")
print("  |_   _|  ")
print("    | |    ")
print("    | |    ")
print("    |_|    ")

print("   __ __   ")
print("  | | | |  ")
print("  | | | |  ")
print("  | |_| |  ")
print("   \___/   ")

print("  __     __") 
print("  \ \   / /")
print("   \ \ / / ")
print("    \ V /  ")
print("     \_/   ")

print("  __        __ ")
print("  \ \      / / ")
print("   \ \ /\ / /  ")
print("    \ V  V /   ")
print("     \_/\_/    ")

print("  __  __ ")
print("  \ \/ / ")
print("   \  /  ")
print("   /  \  ")
print("  /_/\_\ ")


print("  __   __  ")
print("  \ \ / /  ")
print("   \ V /   ")
print("    | |    ")
print("    |_|    ")

print("  ______  ")
print("  |__  / ")
print("    / /  ")
print("   / /_  ")
print("  /____| ")
print("         ")
